// AUTO-GENERATED by scripts/build-data.mjs. Do not edit.
export declare const COUNTRIES: Record<string, { name: string }>;
export declare const COUNTRIES_LOCALIZED: Record<string, Record<string, string>>;
export declare const STATES: Record<string, Record<string, string>>;
export declare const STATES_LOCALIZED: Record<string, Record<string, Record<string, string>>>;
